name: generate github stats

on:
  schedule:
    - cron: "30 12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: generate-github-stats
        uses: jstrieb/github-stats@master
        with:
          username: zanuartri
          access_token: ${{ secrets.ACCESS_TOKEN }}
          exclude_langs: "HTML,CSS"
